### ISSUE TITLE
Peer-to-peer code review exercise (Week 3, Module 2)

### ISSUE THREAD

**Issue by TechnoAndy** [Daphineatim/JavaScript-best-practice#2]
Hi @Daphineatim 

# Great job on your code 😎

![StandingOvationGIF](https://user-images.githubusercontent.com/47176316/193891409-eadb1aa6-32b3-4098-956d-f2d1fe1fa9b0.gif)

- The functions all work as required 👌👍
- All linters are passing👌👍
- Very professional README 👌👍
- Your code is very neat and easy to read 👌👍
- Coding best practises used 👌👍

Keep up the great work 🎆

**Comment by Daphineatim** [comment]
Thank you so much for the feedback! 👏
